# Generated by Django 5.1.6 on 2025-02-14 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='CPUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreCount', models.PositiveIntegerField()),
                ('performanceGHz', models.DecimalField(decimal_places=2, max_digits=6)),
                ('perfBoostGHz', models.DecimalField(decimal_places=2, max_digits=6)),
                ('microArch', models.CharField(max_length=255)),
                ('integratedGraphics', models.CharField(max_length=255)),
                ('integratedHeatSpreader', models.CharField(max_length=255)),
                ('siliconType', models.CharField(max_length=255)),
                ('substrate', models.CharField(max_length=255)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
