# Generated by Django 5.1.6 on 2025-02-24 17:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_perfboostghz_cpu_baseclockspeedghz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderObject',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='prod_id',
            new_name='productId',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='prod_id',
            new_name='productId',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='prod_id',
            new_name='productId',
        ),
        migrations.RenameField(
            model_name='memory',
            old_name='prod_id',
            new_name='productId',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='prod_id',
            new_name='productId',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='memoryGB',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='memoryType',
        ),
        migrations.CreateModel(
            name='CPUCooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coolerType', models.CharField(max_length=255)),
                ('fanSizeMM', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('rpm', models.PositiveIntegerField()),
                ('noiseLeveldBA', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('tdpWatts', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('material', models.CharField(max_length=255)),
                ('socketCompatibility', models.CharField(max_length=255)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenSizeInches', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('resolution', models.CharField(max_length=255)),
                ('refreshRateHz', models.PositiveIntegerField()),
                ('responseTimeMS', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('panelType', models.CharField(max_length=255)),
                ('aspectRatio', models.CharField(max_length=255)),
                ('ports', models.CharField(max_length=255)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orderobject')),
            ],
        ),
        migrations.CreateModel(
            name='PCCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formFactor', models.CharField(max_length=255)),
                ('maxGPULengthMM', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('maxCPUCoolerHeightMM', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('maxPSULengthMM', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('material', models.CharField(max_length=255)),
                ('sidePanelType', models.CharField(max_length=255)),
                ('expansionSlots', models.PositiveIntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wattage', models.PositiveIntegerField()),
                ('efficiencyRating', models.CharField(max_length=255)),
                ('formFactor', models.CharField(max_length=255)),
                ('modularity', models.CharField(max_length=255)),
                ('fanSizeMM', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('protections', models.CharField(max_length=255)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storageType', models.CharField(max_length=255)),
                ('capacityGB', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('readSpeedMBps', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('writeSpeedMBps', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('interface', models.CharField(max_length=255)),
                ('formFactor', models.CharField(max_length=255)),
                ('nandType', models.CharField(max_length=255)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='orderobject',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.user'),
        ),
    ]
