# Generated by Django 5.1.6 on 2025-02-25 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orderobject_user_rename_prod_id_cpu_productid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderobject',
            name='userId',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='productId',
            new_name='prod_id',
        ),
        migrations.RenameField(
            model_name='cpucooler',
            old_name='productId',
            new_name='prod_id',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='productId',
            new_name='prod_id',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='productId',
            new_name='prod_id',
        ),
        migrations.RenameField(
            model_name='memory',
            old_name='productId',
            new_name='prod_id',
        ),
        migrations.RenameField(
            model_name='monitor',
            old_name='productId',
            new_name='prod_id',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='productId',
            new_name='prod_id',
        ),
        migrations.RenameField(
            model_name='pccase',
            old_name='productId',
            new_name='prod_id',
        ),
        migrations.RenameField(
            model_name='psu',
            old_name='productId',
            new_name='prod_id',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='productId',
            new_name='prod_id',
        ),
        migrations.AddField(
            model_name='gpu',
            name='memoryGB',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpu',
            name='memoryType',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='mainImage',
            field=models.CharField(default='missing.png', max_length=255),
        ),
        migrations.DeleteModel(
            name='OrderListing',
        ),
        migrations.DeleteModel(
            name='OrderObject',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
