# Generated by Django 5.1.6 on 2025-03-28 23:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mainImage', models.CharField(default='missing.png', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('claimed', 'Claimed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('finished', 'Finished')], default='placed', max_length=20)),
                ('employeeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_claimed_order', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PCCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formFactor', models.CharField(max_length=255)),
                ('maxGPULengthMM', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('maxCPUCoolerHeightMM', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('maxPSULengthMM', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('material', models.CharField(max_length=255)),
                ('sidePanelType', models.CharField(max_length=255)),
                ('expansionSlots', models.PositiveIntegerField()),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('employeeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_claimed_order_items', to=settings.AUTH_USER_MODEL)),
                ('orderId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order_items', to=settings.AUTH_USER_MODEL)),
                ('productId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(max_length=255)),
                ('chipset', models.CharField(max_length=255)),
                ('formFactor', models.CharField(max_length=255)),
                ('maxMemoryGB', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('maxMemorySlots', models.PositiveIntegerField()),
                ('printedCircuitBoard', models.CharField(max_length=255)),
                ('voltageRegulator', models.CharField(max_length=255)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenSizeInches', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('resolution', models.CharField(max_length=255)),
                ('refreshRateHz', models.PositiveIntegerField()),
                ('responseTimeMS', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('panelType', models.CharField(max_length=255)),
                ('aspectRatio', models.CharField(max_length=255)),
                ('ports', models.CharField(max_length=255)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoryType', models.CharField(max_length=255)),
                ('speedMHz', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacityGB', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('casLatency', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('modules', models.PositiveIntegerField()),
                ('printedCircuitBoard', models.CharField(max_length=255)),
                ('chips', models.CharField(max_length=255)),
                ('heatsink', models.CharField(max_length=255)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='missing.png', max_length=255)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chipset', models.CharField(max_length=255)),
                ('memoryType', models.CharField(max_length=255)),
                ('memoryGB', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('baseClockSpeedGHz', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('boostClockSpeedGHz', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('lengthMM', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('widthMM', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('gpuChip', models.CharField(max_length=255)),
                ('vramType', models.CharField(max_length=255)),
                ('vramGB', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='CPUCooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coolerType', models.CharField(max_length=255)),
                ('fanSizeMM', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('rpm', models.PositiveIntegerField()),
                ('noiseLeveldBA', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('tdpWatts', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('material', models.CharField(max_length=255)),
                ('socketCompatibility', models.CharField(max_length=255)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreCount', models.PositiveIntegerField()),
                ('baseClockSpeedGHz', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('boostClockSpeedGHz', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('microArch', models.CharField(max_length=255)),
                ('integratedGraphics', models.CharField(max_length=255)),
                ('integratedHeatSpreader', models.CharField(max_length=255)),
                ('siliconType', models.CharField(max_length=255)),
                ('substrate', models.CharField(max_length=255)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wattage', models.PositiveIntegerField()),
                ('efficiencyRating', models.CharField(max_length=255)),
                ('formFactor', models.CharField(max_length=255)),
                ('modularity', models.CharField(max_length=255)),
                ('fanSizeMM', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('protections', models.CharField(max_length=255)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storageType', models.CharField(max_length=255)),
                ('capacityGB', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('readSpeedMBps', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('writeSpeedMBps', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('interface', models.CharField(max_length=255)),
                ('formFactor', models.CharField(max_length=255)),
                ('nandType', models.CharField(max_length=255)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
