# Generated by Django 5.1.6 on 2025-05-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timesOrdered',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
