# Generated by Django 5.1.6 on 2025-05-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_timesordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='incompatibilites',
            field=models.ManyToManyField(blank=True, related_name='incompatible_with_products', to='shop.product'),
        ),
    ]
