# Generated by Django 5.1.6 on 2025-05-02 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_incompatibilites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='incompatibilites',
            new_name='incompatibilities',
        ),
    ]
